---

#use apt to install Git
- name: install git 
  apt:
    name: git
    state: present
    update_cache: yes

#delete old index.html file from default Document root /var/www/html (better to create a new vhost but
## this is just for demo)
# - name: delete of index.html file from default Document Root
#   file:
#     path: /var/www/html/index.html
#     state: absent

# clone the specified repo (variable "repository" must have a value in /roles/webapp/defaults/main.yml file)
## and deploy it to the default Document Root on the apache servers which is /var/www/html
- name: copy files from repo and deploy to webserver
  git:
    repo: "{{ repository }}"
    dest: /home/home/website
    
- name: copy all website files except .git and readme
  synchronize:
    src: /home/ubuntu/website
    dest: /var/www/html
    rsync_opts:
      - "--exclude=.git"
        "--exclude=README.md"
  delegate_to: "{{ inventory_hostname }}"    